### ISSUE TITLE
повторення коду

### ISSUE THREAD

**Issue by pecourses** [balhan84/CSS_Homework1#5]
https://github.com/balhan84/CSS_Homework1/blob/058f8339ee80af22a9e68fc58652eed6147f2c5e/assets/css/styles.css#L126-L138
- тут стилі майже повторюються. Щоб по два рази не писати одне й те саме, та не виправляти при підтримці, то зазвичай однакове прописують разом в єдиному джерелі істини:
```css
.section-bottom1,
.section-bottom2 {
  padding: 35.2px;
  color: #ffffff;
  width: 50%;
}

.section-bottom1 {
  background-color: blue;
}

.section-bottom2 {
  background-color: #333;
}

``` 
- нижче `.footer-info1` та `.footer-info2` однакові, тут варто залашити один клас `.footer-info`
- є кольори, що повторюються, буде плюсом винести в css-змінні
